import { Router, type IRouter } from "express";
import healthRouter from "./health";
import contactRouter from "./contact";
import newsletterRouter from "./newsletter";
import chatRouter from "./chat";
import ticketsRouter from "./tickets";
import bookingsRouter from "./bookings";
import adminRouter from "./admin";
import contactsRouter from "./contacts";
import blogAdminRouter from "./blog-admin";
import emailRouter from "./email-campaigns";
import statsRouter from "./admin-stats";
import contentGenRouter from "./content-gen";
import websiteAnalyticsRouter from "./analytics-website";
import placesRouter from "./places";
import refundsRouter from "./refunds";
import financeRouter from "./finance";
import userAuthRouter from "./user-auth";
import profilesRouter from "./profiles";
import adminProfilesRouter from "./admin-profiles";
import aiProfileAssistRouter from "./ai-profile-assist";
import eventProjectsRouter from "./event-projects";
import contentPipelineRouter from "./content-pipeline";

const router: IRouter = Router();

router.use(healthRouter);
router.use(contactRouter);
router.use(newsletterRouter);
router.use(chatRouter);
router.use(ticketsRouter);
router.use(bookingsRouter);
router.use(adminRouter);
router.use(contactsRouter);
router.use(blogAdminRouter);
router.use(emailRouter);
router.use(statsRouter);
router.use(contentGenRouter);
router.use(websiteAnalyticsRouter);
router.use(placesRouter);
router.use(refundsRouter);
router.use(financeRouter);
router.use(userAuthRouter);
router.use(profilesRouter);
router.use(adminProfilesRouter);
router.use(aiProfileAssistRouter);
router.use(eventProjectsRouter);
router.use(contentPipelineRouter);

export default router;
