export const SEED_PLACES = [
  {
    slug: "marble-rosebank-johannesburg",
    name: "Marble",
    tagline: "The video that started everything — 191K views, Rosebank",
    category: "Restaurant",
    cuisine: "Wood-fired contemporary South African",
    neighborhood: "Rosebank",
    city: "Johannesburg",
    address: "2 Keyes Ave, Rosebank, Johannesburg, 2196",
    priceRange: "RRRR",
    tiktokViews: 191800,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80",
    excerpt: "I went to Marble in Rosebank and I get why this one hit 191K. The moment you walk in, the fire-cooking setup isn't a gimmick — you smell the wood, you feel the heat from the kitchen, and the room has an energy that other restaurants try to manufacture and just can't.",
    description: "I went to Marble in Rosebank and I get why this one hit 191K. It's the most-watched post on the Woman of Taste page and honestly, it deserves to be.\n\nWhen I walked in, the first thing I noticed was the smell. Wood smoke, slow-cooked meat, a kitchen that's actually working. The open fire setup is right there — not behind glass or hidden away. You can see it.\n\nI had the bone marrow to start and then the dry-aged beef. The bone marrow came with bread that honestly could be its own course. The beef was cooked exactly the way I asked. Nothing overworked.\n\nMy honest take: this is a room that has figured out what it is and keeps delivering it. The service is knowledgeable without being stiff. The wine list is strong South African. If you're celebrating something, it lands. If you're just there for dinner, it still delivers. I'd go back — and I have.",
    highlights: [
      "191K TikTok views — my most-watched post ever on WOT",
      "Open wood-fire kitchen — the smoke hits you before the menu does",
      "Dry-aged beef sourced from South African farms",
      "Strong South African wine list",
    ],
    mustTry: [
      { name: "Bone marrow + bread", note: "This is where dinner starts. Don't skip it." },
      { name: "Dry-aged beef", note: "Ask what the cut of the day is and go with that" },
      { name: "Something from the SA wine list", note: "They know their producers here" },
    ],
    vibe: "Fire-lit, warm and a bit dramatic — in the best way. Dress for the room.",
    perfectFor: ["Birthdays and celebrations", "A date that needs to land", "When you want to impress someone", "When Joburg feels worth it"],
    tags: ["Fine Dining", "Wood-Fired", "Rosebank", "Special Occasion"],
    openingHours: "Mon–Sat 12:00–22:00, Sun 12:00–21:00",
    reservations: true,
    website: "https://www.marble.restaurant",
    instagramHandle: "@marblejoburg",
    seoKeywords: ["Marble restaurant Rosebank Johannesburg", "best restaurants Joburg 2025", "wood-fired restaurant Johannesburg"],
    status: "published",
    featured: true,
    datePosted: "2024-10-01",
  },
  {
    slug: "farmhouse-58-muldersdrift",
    name: "Farmhouse 58",
    tagline: "The Muldersdrift stay that hit 166K — and earned every single one",
    category: "Stay",
    cuisine: "",
    neighborhood: "Muldersdrift",
    city: "Johannesburg",
    address: "Farmhouse 58, Muldersdrift, Gauteng",
    priceRange: "RRR",
    tiktokViews: 167500,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&q=80",
    excerpt: "I drove out to Muldersdrift on a whim and this is what I found. Farmhouse 58 is one of those places that makes you remember why you live in Joburg. 166K people watched this one — I understand why.",
    description: "I drove out to Muldersdrift and found Farmhouse 58, and this became one of the most-watched videos on the Woman of Taste page — 166K views and it keeps going.\n\nWhat I didn't expect was how genuinely restorative it is. You leave Joburg's pace behind the moment you turn off the main road. The accommodation sits on a working farm with a pool and the kind of quiet that you forget exists when you're living in Sandton or Rosebank.\n\nI spent time by the pool and I woke up early for the farm surroundings and honestly both were worth it. The light out there in the morning is something else.\n\nMy honest take: this isn't a hotel. It's a reset. The kind you need more than you realise. I'd go back for a birthday, a girls' trip, or genuinely just to breathe differently for a night or two.",
    highlights: [
      "167K TikTok views — one of the most-watched WOT features ever",
      "Farm accommodation with pool and open green landscapes",
      "Muldersdrift location — about an hour from central Joburg",
      "That particular kind of quiet that city life takes away",
    ],
    mustTry: [
      { name: "Morning by the pool", note: "The pool is central to the experience. Start there." },
      { name: "Sunrise on the farm", note: "Wake up earlier than you usually would. It's worth it." },
    ],
    vibe: "Farm-calm, beautiful and genuinely restorative. Leave your schedule at home.",
    perfectFor: ["Weekend getaways", "Birthday escapes", "Girls' trips", "When you just need to breathe"],
    tags: ["Stay", "Muldersdrift", "Farm Accommodation", "Weekend Escape"],
    openingHours: "",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["Farmhouse 58 Muldersdrift stay", "farm accommodation near Johannesburg", "weekend getaway Joburg"],
    status: "published",
    featured: true,
    datePosted: "2024-10-10",
  },
  {
    slug: "egrek-cinema-parkhurst",
    name: "Egrek Cinema",
    tagline: "Parkhurst outdoor cinema — 69.5K views and still one of my favourite Joburg evenings",
    category: "Experience",
    cuisine: "",
    neighborhood: "Parkhurst",
    city: "Johannesburg",
    address: "Parkhurst Square, Block A, 4th Ave, Parkhurst, Johannesburg",
    priceRange: "RR",
    tiktokViews: 69500,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&q=80",
    excerpt: "I went to Egrek Cinema in Parkhurst and I genuinely didn't want the evening to end. An outdoor cinema on 4th Ave — the kind of thing that makes you feel like Joburg is looking after you.",
    description: "I went to Egrek Cinema on a Friday evening and honestly, 69.5K views later, I still think about this one.\n\nIt's an outdoor cinema experience at Parkhurst Square on 4th Ave — one of my favourite streets in the city. You get there early, you walk the strip, maybe eat somewhere first, and then you settle in under the sky with a screen in front of you.\n\nWhat got me wasn't just the film. It was the atmosphere. The community of it. People with blankets, kids, couples, groups of women — everyone came to be somewhere special for an evening.\n\nMy honest take: this is the kind of Joburg evening that reminds you how good this city can be when it's doing what it does best. I'd go back every time it runs.",
    highlights: [
      "69.5K TikTok views on the WOT page",
      "Outdoor cinema in the heart of Parkhurst",
      "4th Ave location — walk and eat before the film",
      "That communal energy that Joburg does really well",
    ],
    mustTry: [
      { name: "Dinner on 4th Ave first", note: "Walk the strip before settling in for the film" },
      { name: "Blanket and snacks setup", note: "Come prepared — it makes the experience" },
    ],
    vibe: "Warm, communal and cinematic. Joburg evenings at their most charming.",
    perfectFor: ["Date nights", "Girls' evenings out", "Birthday celebrations", "When Joburg feels like a gift"],
    tags: ["Experience", "Parkhurst", "Outdoor Cinema", "Date Night"],
    openingHours: "",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["Egrek Cinema Parkhurst Johannesburg", "outdoor cinema Joburg", "things to do Parkhurst"],
    status: "published",
    featured: false,
    datePosted: "2024-11-01",
  },
  {
    slug: "san-deck-sandton-city",
    name: "San Deck",
    tagline: "Sandton City's rooftop restaurant — 91.7K views and I completely understand why",
    category: "Restaurant",
    cuisine: "Mediterranean-inspired",
    neighborhood: "Sandton",
    city: "Johannesburg",
    address: "Sandton City, Sandton, Johannesburg",
    priceRange: "RRR",
    tiktokViews: 91700,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200&q=80",
    excerpt: "San Deck at Sandton City hit 91.7K views and it's one of the most visually stunning restaurant experiences in Joburg. I went up there and honestly wasn't prepared for how good the views and the food both turned out to be.",
    description: "San Deck is on the rooftop at Sandton City and it hit 91.7K views on the Woman of Taste page — the second highest ever after Marble.\n\nI went up there and the first thing that struck me was the view. Sandton from up there at a certain hour of the day looks genuinely beautiful. The light changes, the city goes warm, and you're sitting at a table with a glass of something cold.\n\nThe food is Mediterranean-inspired — light, confident cooking that doesn't overstay its welcome. I had seafood and something from the sharing section and both were exactly what I wanted.\n\nMy honest take: this is a lunch place as much as a dinner place. Getting there at the right time of day matters. If you go at 1pm on a Saturday and the weather is doing its thing, you'll understand why this video resonated with so many people. I think about this rooftop often.",
    highlights: [
      "91.7K TikTok views — second highest ever on the WOT page",
      "Rooftop location at Sandton City with city views",
      "Mediterranean-inspired menu — seafood, sharing plates",
      "The light at the right time of day is genuinely special",
    ],
    mustTry: [
      { name: "Seafood option", note: "The Mediterranean focus means this is where the kitchen shines" },
      { name: "Go at lunch", note: "The rooftop at midday on a good weather day is something else" },
      { name: "Cocktail with the view", note: "Order something to drink and just take it in first" },
    ],
    vibe: "Airy, open and completely Sandton at its best. The view does half the work.",
    perfectFor: ["Sandton lunch dates", "Celebrating with a view", "When you need Joburg to feel generous", "Group meals with a setting worth talking about"],
    tags: ["Restaurant", "Sandton", "Rooftop", "Mediterranean", "Views"],
    openingHours: "",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["San Deck Sandton City rooftop restaurant", "rooftop restaurants Johannesburg", "Sandton City dining"],
    status: "published",
    featured: true,
    datePosted: "2024-11-05",
  },
  {
    slug: "bounce-fourways",
    name: "BOUNCE",
    tagline: "The Fourways experience that hit 100K — I went and completely lost track of time",
    category: "Experience",
    cuisine: "",
    neighborhood: "Fourways",
    city: "Johannesburg",
    address: "Fourways, Johannesburg, Gauteng",
    priceRange: "RR",
    tiktokViews: 100000,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&q=80",
    excerpt: "I went to BOUNCE in Fourways and I genuinely did not expect to have as much fun as I did. This is one of those experiences that looks like it's for kids and then you get there and it's actually for everyone.",
    description: "BOUNCE in Fourways hit 100K views on the Woman of Taste page and it's one of the pinned posts on my profile — that tells you something.\n\nI went thinking it would be a quick fun thing. I stayed for much longer than I planned. The trampoline park setup is bigger than you expect and the energy inside is completely different to anything else in Joburg's entertainment landscape.\n\nWhat I noticed: it doesn't matter what age group you're in. I saw women my age completely letting go in there — jumping, laughing, doing things they'd never normally do. That's the appeal. You come in doing one thing and leave feeling lighter.\n\nMy honest take: BOUNCE is one of those experiences that's genuinely about how it makes you feel, not just what you do. I'd go back for a birthday, a group outing, or honestly just when I need to move my body and have fun doing it.",
    highlights: [
      "100K TikTok views — one of my pinned posts on the WOT page",
      "Trampoline park experience — much bigger than you expect",
      "Energy inside is completely different to anything else in Joburg",
      "Works for every age group — not just kids",
    ],
    mustTry: [
      { name: "Just jump", note: "Don't overthink it. Get in and go." },
      { name: "Go with a group", note: "The energy multiplies when you're there with people" },
    ],
    vibe: "High-energy, childlike in the best way and completely freeing. Go with people.",
    perfectFor: ["Group outings", "Birthday experiences", "When you need to move and laugh", "When Joburg needs to feel fun again"],
    tags: ["Experience", "Fourways", "Active", "Group Fun"],
    openingHours: "",
    reservations: false,
    website: "",
    instagramHandle: "",
    seoKeywords: ["BOUNCE Fourways trampoline park", "fun things to do Johannesburg", "Fourways experiences Joburg"],
    status: "published",
    featured: true,
    datePosted: "2024-11-10",
  },
  {
    slug: "the-tasting-room-johannesburg",
    name: "The Tasting Room",
    tagline: "44.4K views — fine dining that I was not fully prepared for",
    category: "Restaurant",
    cuisine: "Contemporary fine dining",
    neighborhood: "Johannesburg",
    city: "Johannesburg",
    address: "Johannesburg, Gauteng",
    priceRange: "RRRR",
    tiktokViews: 44400,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=1200&q=80",
    excerpt: "I went to The Tasting Room and I wasn't fully ready for what arrived at the table. 44.4K views later, I think most people who watched that video felt the same way.",
    description: "The Tasting Room hit 44.4K views on the Woman of Taste page and I think what resonated was the same thing that resonated with me when I sat down — this is fine dining that feels personal, not performative.\n\nA tasting menu means you're handing the kitchen your evening. You're saying: show me what you've got. And what arrived at the table, course by course, was genuinely considered. Nothing landed without intention.\n\nThe wine pairing elevated it. The service was knowledgeable in a way that felt like conversation rather than presentation.\n\nMy honest take: this is an occasion restaurant. You don't go here on a Tuesday for no reason. You go here when you want the evening to mean something — when you want the food to be the event. I'd go back for a milestone. And I'd count on it delivering.",
    highlights: [
      "44.4K TikTok views on the WOT page",
      "Tasting menu format — the kitchen takes over your evening",
      "Wine pairing that genuinely adds to the experience",
      "Service that feels like conversation",
    ],
    mustTry: [
      { name: "Full tasting menu", note: "This is not the place to order à la carte. Go the distance." },
      { name: "Wine pairing", note: "Worth every extra rand — it changes how each course lands" },
    ],
    vibe: "Considered, intimate and quietly impressive. This is dining as an event.",
    perfectFor: ["Milestone celebrations", "When food is the whole point of the evening", "Impressing someone who eats seriously", "Treating yourself properly"],
    tags: ["Fine Dining", "Tasting Menu", "Special Occasion", "Johannesburg"],
    openingHours: "",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["The Tasting Room Johannesburg fine dining", "tasting menu restaurants Joburg", "best fine dining Johannesburg 2025"],
    status: "published",
    featured: false,
    datePosted: "2024-11-15",
  },
  {
    slug: "northriding-ice-rink",
    name: "The Ice Rink, Northriding",
    tagline: "39.7K views — a Joburg experience I genuinely didn't see coming",
    category: "Experience",
    cuisine: "",
    neighborhood: "Northriding",
    city: "Johannesburg",
    address: "Northriding, Randburg, Gauteng",
    priceRange: "R",
    tiktokViews: 39700,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1579807424264-0f88ef3bd066?w=1200&q=80",
    excerpt: "I went to the ice rink in Northriding expecting nothing and left genuinely smiling. 39.7K people watched this one and I think it's because it's the kind of Joburg experience that surprises you.",
    description: "The ice rink at Northriding hit 39.7K views on the Woman of Taste page and the reason is simple: it's genuinely surprising.\n\nYou don't associate Joburg with ice rinks. You go there half-expecting it to feel like a novelty that doesn't quite land. But I went, got my skates on, and the experience delivered in a way I wasn't ready for.\n\nThe rink itself is well-maintained. The energy inside is completely different to any other Joburg venue — cold air, the sound of blades, people figuring out their balance. There's something equalising about that.\n\nMy honest take: this is the kind of outing that's perfect for when you want to do something different without spending a lot. It's active, it's fun, it's genuinely Joburg doing something unexpected. I'd take a group of friends there on a Saturday afternoon.",
    highlights: [
      "39.7K TikTok views on the WOT page",
      "Ice skating in Joburg — not what people expect but it delivers",
      "Northriding location — accessible from across the northern suburbs",
      "Accessible entry price — high fun, low spend",
    ],
    mustTry: [
      { name: "Just get on the ice", note: "It takes about 10 minutes to find your footing. Worth it." },
      { name: "Go with a group", note: "The experience multiplies when other people are figuring it out too" },
    ],
    vibe: "Cold, energetic and completely unlike the rest of Joburg. That's the point.",
    perfectFor: ["Group outings", "Something different on a weekend", "When Joburg needs to surprise you", "Date activities that actually create a memory"],
    tags: ["Experience", "Northriding", "Ice Skating", "Active", "Group Fun"],
    openingHours: "",
    reservations: false,
    website: "",
    instagramHandle: "",
    seoKeywords: ["ice rink Northriding Johannesburg", "ice skating Joburg", "things to do Northriding Randburg"],
    status: "published",
    featured: false,
    datePosted: "2024-11-20",
  },
  {
    slug: "chunky-chow-sandton",
    name: "Chunky Chow",
    tagline: "Pan-Asian in Sandton — 39.4K views and the dumplings got me",
    category: "Restaurant",
    cuisine: "Pan-Asian fusion",
    neighborhood: "Sandton",
    city: "Johannesburg",
    address: "Sandton, Johannesburg",
    priceRange: "RRR",
    tiktokViews: 39400,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=1200&q=80",
    excerpt: "I went to Chunky Chow in Sandton and left with 39.4K views and a serious craving I keep going back to satisfy. Pan-Asian done properly in the middle of Joburg's most cosmopolitan suburb.",
    description: "Chunky Chow in Sandton hit 39.4K views on the Woman of Taste page and the reason is simple: the food is genuinely good and I wasn't shy about showing that.\n\nPan-Asian means the kitchen draws from across multiple Asian culinary traditions. At Chunky Chow, that translates to a menu that keeps you engaged — dim sum, wok cooking, flavours that are layered and confident.\n\nI started with the dim sum selection and that set the tone for everything that followed. What I noticed: nothing felt like it was trying too hard. The food was sure of itself.\n\nMy honest take: this is one of my Sandton go-tos now. The location works for post-shopping meals, business lunches, date dinners. The food holds up for all of those. I'd go back specifically for the dumplings and the wok dishes.",
    highlights: [
      "39.4K views on the Woman of Taste TikTok feature",
      "Pan-Asian — dim sum, wok cooking, layered confident flavours",
      "Sandton location — works for any part of the day",
      "The kind of menu that rewards ordering widely",
    ],
    mustTry: [
      { name: "Dim sum selection", note: "Start here. This is where you understand what the kitchen is doing." },
      { name: "Wok-fired mains", note: "Where the flavour reaches its peak" },
    ],
    vibe: "Dynamic, flavour-forward and visually striking. Sandton dining with real personality.",
    perfectFor: ["Adventurous eaters", "Business dinners", "Date nights", "Post-Sandton City exploration"],
    tags: ["Restaurant", "Pan-Asian", "Sandton", "Fusion Dining"],
    openingHours: "Tue–Sun 12:00–22:00",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["Chunky Chow Sandton Pan-Asian restaurant", "Pan-Asian restaurants Joburg", "dumplings Sandton Johannesburg"],
    status: "published",
    featured: false,
    datePosted: "2024-09-15",
  },
  {
    slug: "the-test-bakery-braamfontein",
    name: "The Test Bakery",
    tagline: "Braam's cult bakery — 34K views and the bread completely changed my morning",
    category: "Restaurant",
    cuisine: "Artisan bakery & café",
    neighborhood: "Braamfontein",
    city: "Johannesburg",
    address: "Braamfontein, Johannesburg",
    priceRange: "R",
    tiktokViews: 34000,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200&q=80",
    excerpt: "I went to The Test Bakery in Braamfontein and the bread alone made me want to tell everyone I know. 34K views later, I think they all watched.",
    description: "The Test Bakery in Braamfontein hit 34K views on the Woman of Taste page and honestly, this one was about showing people that Joburg's creative quarter has something genuinely excellent in it.\n\nI went on a Saturday morning. Braam was doing what Braam does — art, people, energy. And then I walked into the bakery and everything slowed down in the best way.\n\nThe sourdough is the thing. You can smell it before you're through the door. I ordered a loaf and a pastry and a flat white, found a spot, and spent an hour just being in a really good place.\n\nMy honest take: The Test Bakery is the kind of spot that makes you feel like you discovered something — even after 34K people have already found it. I go back regularly. The bread is that good.",
    highlights: [
      "34K TikTok views on the WOT Braamfontein feature",
      "The sourdough is the reason people keep coming back",
      "Braamfontein location — walk the neighbourhood while you're here",
      "Accessible price for exceptional craft",
    ],
    mustTry: [
      { name: "Sourdough loaf", note: "The bread that built the reputation" },
      { name: "Pastry of the day", note: "Whatever is at the counter when you arrive" },
      { name: "Flat white", note: "Coffee is taken seriously here" },
    ],
    vibe: "Creative, unhurried and genuinely Joburg. Neighbourhood energy at its best.",
    perfectFor: ["Saturday morning starts", "Braamfontein explorations", "When you need something made with real care", "Solo dining with a book"],
    tags: ["Restaurant", "Bakery", "Braamfontein", "Coffee", "Artisan"],
    openingHours: "",
    reservations: false,
    website: "",
    instagramHandle: "",
    seoKeywords: ["The Test Bakery Braamfontein Johannesburg", "best bakery Joburg", "sourdough bread Johannesburg"],
    status: "published",
    featured: false,
    datePosted: "2024-09-20",
  },
  {
    slug: "nineteen-on-fourth-parkhurst",
    name: "Nineteen on Fourth",
    tagline: "My Parkhurst baseline — 30.2K views and I keep going back",
    category: "Restaurant",
    cuisine: "Contemporary café dining",
    neighborhood: "Parkhurst",
    city: "Johannesburg",
    address: "19 4th Ave, Parkhurst, Johannesburg, 2193",
    priceRange: "RR",
    tiktokViews: 30200,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=1200&q=80",
    excerpt: "Nineteen on Fourth is the Parkhurst restaurant I come back to without thinking too hard. 30.2K people watched that video — I think it's because this place feels like what a good regular spot should feel like.",
    description: "Nineteen on Fourth sits on 4th Avenue in Parkhurst and it's become my baseline for what a neighbourhood restaurant should be. 30.2K TikTok views later, I think the community agrees.\n\nI've been here for breakfast, brunch, lunch and evening drinks. Something about the consistency is what gets me. You walk in knowing what you're getting and it delivers every single time.\n\nThe al fresco seating on 4th Ave is part of it. That strip is one of the best people-watching spots in Joburg and Nineteen on Fourth gives you a front-row seat.\n\nMy honest take: this is the restaurant you come back to. Not always for the most exciting meal of your life, but for the meal that reliably makes you feel good. That's its own kind of valuable. I go here when I need Joburg to feel familiar and warm.",
    highlights: [
      "30.2K TikTok views on the WOT feature",
      "4th Avenue location — Joburg's best café strip",
      "All-day dining from morning coffee to dinner",
      "Outdoor seating with excellent people-watching",
    ],
    mustTry: [
      { name: "Breakfast plate", note: "One of the better Joburg breakfasts on the strip" },
      { name: "Coffee and pastry", note: "For a quick stop between other 4th Ave explorations" },
    ],
    vibe: "Neighbourhood warmth, consistent and always pleasant. Parkhurst at its best.",
    perfectFor: ["Weekend brunches", "Parkhurst mornings", "Casual lunch dates", "When you need reliable and good"],
    tags: ["Restaurant", "Parkhurst", "Brunch", "All-Day Dining", "4th Avenue"],
    openingHours: "",
    reservations: false,
    website: "",
    instagramHandle: "",
    seoKeywords: ["Nineteen on Fourth Parkhurst Johannesburg", "restaurants Parkhurst 4th Avenue", "brunch Parkhurst Joburg"],
    status: "published",
    featured: false,
    datePosted: "2024-09-25",
  },
  {
    slug: "club-como-morningside",
    name: "Club Como",
    tagline: "Morningside at night — 25.9K views and I stayed longer than I planned",
    category: "Restaurant",
    cuisine: "Contemporary dining and cocktail bar",
    neighborhood: "Morningside",
    city: "Johannesburg",
    address: "Morningside, Sandton, Johannesburg",
    priceRange: "RRR",
    tiktokViews: 25900,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=1200&q=80",
    excerpt: "I went to Club Como in Morningside for dinner and ended up staying for the night. 25.9K people watched that happen and I think most of them understood why.",
    description: "Club Como in Morningside hit 25.9K views on the Woman of Taste page and it's one of those places that's difficult to leave at a reasonable hour.\n\nI went for dinner. The food was good — confident, well-executed, the kind of menu that knows what it's doing. But what kept the evening going was the energy of the room as the night progressed.\n\nMorningside has a particular Joburg sophistication to it and Club Como fits that perfectly. The crowd understands how to be in a room. The cocktails were strong. The music hit the right register.\n\nMy honest take: this is a dinner-that-becomes-a-night-out kind of place. I'd go for the food and stay for how the room feels at 10pm. If you're planning a celebration or just want an evening that has real momentum, Club Como delivers that.",
    highlights: [
      "25.9K TikTok views on the WOT page",
      "Morningside location — Joburg sophistication done properly",
      "Dinner that becomes an evening — the energy builds as the night goes on",
      "Cocktail programme that takes itself seriously",
    ],
    mustTry: [
      { name: "The cocktail list first", note: "Start with a drink before you look at the food menu" },
      { name: "Main course", note: "The kitchen is confident — trust the menu" },
    ],
    vibe: "Sophisticated, evening-ready and the kind of room that gets better as the night goes on.",
    perfectFor: ["Celebration dinners", "Date nights that need momentum", "Group evenings with real energy", "When Joburg nightlife needs to feel premium"],
    tags: ["Restaurant", "Morningside", "Cocktail Bar", "Evening Dining", "Nightlife"],
    openingHours: "",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["Club Como Morningside Johannesburg", "restaurants Morningside Sandton", "nightlife Morningside Joburg"],
    status: "published",
    featured: false,
    datePosted: "2024-12-01",
  },
  {
    slug: "the-potato-shed-waterfall",
    name: "The Potato Shed",
    tagline: "Waterfall comfort food — 25.3K views and I ordered more than I meant to",
    category: "Restaurant",
    cuisine: "Contemporary South African comfort",
    neighborhood: "Waterfall",
    city: "Johannesburg",
    address: "Waterfall, Midrand, Johannesburg",
    priceRange: "RR",
    tiktokViews: 25300,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1544148103-0773bf10d330?w=1200&q=80",
    excerpt: "I went to The Potato Shed in Waterfall expecting something low-key and left genuinely full and pleased with myself. 25.3K people watched me eat too much and I have no regrets.",
    description: "The Potato Shed in Waterfall hit 25.3K views on the Woman of Taste page and the reason is simple: I genuinely enjoyed myself and it showed.\n\nThis is comfort food with real ambition behind it. The kitchen isn't trying to be fine dining — it knows exactly what it is and executes it with confidence. Generous portions, good flavour, the kind of meal that makes you feel looked after.\n\nI ordered more than I planned. The sharing plates were the reason. Everything arrived and I kept saying 'one more'. That's the mark of a kitchen that knows how to cook for actual people.\n\nMy honest take: this is a Waterfall find that punches above its location. If you're in the northern suburbs and you want a meal that delivers comfort without cutting corners on quality, The Potato Shed is worth the drive.",
    highlights: [
      "25.3K TikTok views on the WOT Waterfall feature",
      "Comfort cooking done with real ambition and generosity",
      "Waterfall location — accessible from across northern Joburg",
      "Sharing plates that keep you ordering more",
    ],
    mustTry: [
      { name: "The signature potato dish", note: "The namesake. Try it in whatever current form it appears." },
      { name: "Sharing plates selection", note: "Order widely — they're built for the table" },
    ],
    vibe: "Warm, generous and completely unpretentious. Comfort dining that takes itself seriously.",
    perfectFor: ["Group lunches", "Family meals", "Northern suburbs gatherings", "When you want comfort done properly"],
    tags: ["Restaurant", "Waterfall", "Comfort Food", "Group Dining", "Midrand"],
    openingHours: "",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["The Potato Shed Waterfall Midrand restaurant", "comfort food restaurants Midrand Joburg", "Waterfall restaurants"],
    status: "published",
    featured: false,
    datePosted: "2024-09-28",
  },
  {
    slug: "saint-sandton",
    name: "SAINT",
    tagline: "SAINT arrived in Sandton and I went immediately — 24.6K views",
    category: "Restaurant",
    cuisine: "Contemporary dining bar",
    neighborhood: "Sandton",
    city: "Johannesburg",
    address: "Sandton, Johannesburg",
    priceRange: "RRR",
    tiktokViews: 24600,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&q=80",
    excerpt: "SAINT opened in Sandton and the conversation started immediately. I went to find out what it was about and left with 24.6K people watching me try to explain a room that has to be felt.",
    description: "SAINT in Sandton hit 24.6K views on the Woman of Taste page and what I remember most is how hard it was to leave.\n\nThe room operates at the intersection of dining and bar — the drinks programme is as considered as the food menu and neither one feels secondary. I started at the bar. The cocktail that arrived was exactly right. Then we moved to the table.\n\nThe food is confident small plates and mains with a kitchen that knows the room it's cooking for. The service team understood the pace of the evening and let it breathe.\n\nMy honest take: SAINT has positioned itself as a Sandton destination for evenings that want momentum. You go there and the room carries you somewhere. I think about the atmosphere at SAINT quite a bit.",
    highlights: [
      "24.6K TikTok views on the WOT feature",
      "Bar and dining room in one — cocktails and food given equal attention",
      "Sandton's most interesting opening in a while",
      "The room has energy that builds as the evening goes on",
    ],
    mustTry: [
      { name: "The cocktail list", note: "Start here. The drinks programme tells you what SAINT is." },
      { name: "Small plates to share", note: "Order widely — the menu rewards that approach" },
    ],
    vibe: "Fashionable, energetic and evening-ready. Sandton at its most current.",
    perfectFor: ["After-work drinks into dinner", "Celebrating in style", "Date evenings that need atmosphere", "Group outings"],
    tags: ["Restaurant", "Sandton", "Dining Bar", "Evening Dining", "Cocktails"],
    openingHours: "",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["SAINT restaurant Sandton Johannesburg", "best new restaurants Sandton 2025", "cocktail bar dining Sandton"],
    status: "published",
    featured: false,
    datePosted: "2024-10-05",
  },
  {
    slug: "artistry-sandton",
    name: "Artistry",
    tagline: "Sandton's creative table — 21.8K views and the plating genuinely surprised me",
    category: "Restaurant",
    cuisine: "Contemporary South African",
    neighborhood: "Sandton",
    city: "Johannesburg",
    address: "Sandton, Johannesburg",
    priceRange: "RRR",
    tiktokViews: 21800,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=1200&q=80",
    excerpt: "I went to Artistry in Sandton and the food landed in front of me and I understood the name immediately. 21.8K people watched that reaction and I think they felt it too.",
    description: "Artistry in Sandton hit 21.8K views on the Woman of Taste page and it earns its name in a way that a lot of restaurants that try to be 'artistic' just don't.\n\nWhat I noticed first was the plating. Everything that came to the table looked considered — not precious or overthought, but genuinely cared about. The kitchen has a point of view and it shows in how the food arrives.\n\nBut what impressed me more was that the taste backed the presentation. South African ingredients, contemporary technique, and a chef who seems to actually know why each element is on the plate.\n\nMy honest take: this is a Sandton restaurant worth discovering deliberately. Not stumbled upon — planned. I'd go back for a special evening when I want the food to feel like an occasion.",
    highlights: [
      "21.8K TikTok views on the WOT feature",
      "The plating justifies the name — visually considered from first course",
      "South African ingredients with contemporary technique",
      "A kitchen with a genuine point of view",
    ],
    mustTry: [
      { name: "Whatever is most visually striking on the menu", note: "In a restaurant called Artistry, trust the most ambitious option" },
      { name: "Seasonal main", note: "What the kitchen is proudest of right now will be on the menu" },
    ],
    vibe: "Creative, considered and visually rich. Joburg dining that takes itself seriously.",
    perfectFor: ["Creative industry dinners", "Special evenings", "When presentation matters as much as taste", "Sandton date nights"],
    tags: ["Restaurant", "Sandton", "Contemporary", "Creative Dining", "Fine Dining"],
    openingHours: "",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["Artistry restaurant Sandton Johannesburg", "contemporary South African restaurant Sandton", "fine dining creative Joburg"],
    status: "published",
    featured: false,
    datePosted: "2024-10-10",
  },
  {
    slug: "ethos-rosebank",
    name: "ETHOS",
    tagline: "Rosebank's most thoughtful café — 21.1K views and I stayed for two hours",
    category: "Restaurant",
    cuisine: "Modern café dining",
    neighborhood: "Rosebank",
    city: "Johannesburg",
    address: "Rosebank, Johannesburg",
    priceRange: "RR",
    tiktokViews: 21100,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80",
    excerpt: "I went to ETHOS in Rosebank for a quick coffee and stayed for two hours. 21.1K views and I think everyone who watched understood that feeling.",
    description: "ETHOS in Rosebank hit 21.1K views on the Woman of Taste page and it's the kind of place that keeps you longer than you planned.\n\nI came in for a coffee after something else in Rosebank. The coffee was immediately impressive — single origin, the barista knew exactly what they were doing. Then I ordered something to eat and the food matched the coffee in intention. Nothing casual about how this kitchen operates.\n\nWhat I noticed: the name isn't decorative. ETHOS operates with a genuine belief system about quality, sourcing and how a café should feel. Everything is consistent with that. The space feels considered. The pace is unhurried.\n\nMy honest take: ETHOS is my Rosebank café. It's where I go when I need to work, think or just be somewhere that feels good. I've been back more times than I can count.",
    highlights: [
      "21.1K TikTok views on the WOT Rosebank feature",
      "Coffee programme that takes single-origin seriously",
      "The name ETHOS means something — the whole café operates with intention",
      "Rosebank location — combine with gallery or shopping",
    ],
    mustTry: [
      { name: "Single-origin coffee", note: "Ask the barista what they're proudest of right now" },
      { name: "Daytime plate", note: "The food matches the coffee in quality and care" },
    ],
    vibe: "Considered, unhurried and quality-driven. The Rosebank café I keep coming back to.",
    perfectFor: ["Working mornings", "Post-gallery catch-ups", "Solo dining with intention", "When you need somewhere that gets it right"],
    tags: ["Restaurant", "Rosebank", "Café", "Coffee", "All-Day Dining"],
    openingHours: "",
    reservations: false,
    website: "",
    instagramHandle: "",
    seoKeywords: ["ETHOS Rosebank Johannesburg café", "best coffee Rosebank Joburg", "all-day dining Rosebank"],
    status: "published",
    featured: false,
    datePosted: "2024-10-15",
  },
  {
    slug: "the-station-parkhurst",
    name: "The Station",
    tagline: "Parkhurst finds another one — 19.3K views and I'm still thinking about the food",
    category: "Restaurant",
    cuisine: "Contemporary South African",
    neighborhood: "Parkhurst",
    city: "Johannesburg",
    address: "Parkhurst, Johannesburg",
    priceRange: "RR",
    tiktokViews: 19300,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80",
    excerpt: "I went to The Station in Parkhurst and it earned its place on 4th Ave immediately. 19.3K people watched that meal and I'm glad I shared it — this one deserves to be discovered.",
    description: "The Station in Parkhurst hit 19.3K views on the Woman of Taste page and it's a Parkhurst restaurant that's found its footing on one of Joburg's most competitive strips.\n\nI went for lunch on a weekend. The menu is contemporary South African — familiar ingredients handled with confidence and a point of view. Nothing felt like it was reaching too far or playing it too safe.\n\nThe space has the Parkhurst warmth that the neighbourhood does so well. Good light, good sound levels, service that understands the pace.\n\nMy honest take: The Station is a strong addition to 4th Avenue. Parkhurst is spoiled for choice but this one earns its spot. I'd go back for the food — specifically the way the kitchen handles South African produce.",
    highlights: [
      "19.3K TikTok views on the WOT page",
      "Contemporary South African — familiar ingredients, confident technique",
      "Parkhurst location on 4th Ave — walk the strip before or after",
      "The kind of neighbourhood restaurant that earns repeat visits",
    ],
    mustTry: [
      { name: "Whatever South African produce is on the menu", note: "This kitchen does local ingredients proud" },
      { name: "Weekend lunch", note: "The light in there at midday on a good day is something" },
    ],
    vibe: "Warm, confident and completely Parkhurst. Neighbourhood dining that delivers.",
    perfectFor: ["Parkhurst lunch dates", "Discovering a new regular", "When you want South African cooking done properly", "Weekend explorers"],
    tags: ["Restaurant", "Parkhurst", "South African", "Lunch", "4th Avenue"],
    openingHours: "",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["The Station restaurant Parkhurst Johannesburg", "restaurants 4th Avenue Parkhurst", "South African restaurants Joburg"],
    status: "published",
    featured: false,
    datePosted: "2024-12-05",
  },
  {
    slug: "nomad-fourways",
    name: "Nomad",
    tagline: "Fourways going somewhere — 12K views and the menu surprised me",
    category: "Restaurant",
    cuisine: "Contemporary international",
    neighborhood: "Fourways",
    city: "Johannesburg",
    address: "Fourways, Johannesburg",
    priceRange: "RR",
    tiktokViews: 12000,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1200&q=80",
    excerpt: "I went to Nomad in Fourways expecting a standard northern suburbs restaurant and the menu genuinely surprised me. 12K views — I think people in the north needed to know about this one.",
    description: "Nomad in Fourways hit 12K views on the Woman of Taste page and it's a Fourways restaurant that's doing something more interesting than the area's dining reputation might suggest.\n\nThe name signals the kitchen's intent and the menu backs it up — global flavour influences, eclectic pairings, a restlessness with playing it safe. For a suburb that can sometimes lean predictable in its food options, Nomad is doing something worthwhile.\n\nI ordered across the menu and was engaged from starter to main. The staff take recommendations seriously, which tells you something about how much they trust the kitchen.\n\nMy honest take: if you're in the northern suburbs and you want a meal that keeps you interested, Nomad is the answer. I'd recommend trusting the waiter's suggestion — they know the menu well.",
    highlights: [
      "12K TikTok views on the WOT Fourways feature",
      "Global flavour influences — not the suburban predictability you might expect",
      "Fourways location — northern suburbs dining with ambition",
      "Staff who take their menu knowledge seriously",
    ],
    mustTry: [
      { name: "Ask the waiter", note: "Take the recommendation — it changes with what's working well" },
      { name: "Order across the menu", note: "The range is the point. Explore it." },
    ],
    vibe: "Curious, eclectic and confidently Joburg-north. Food that surprises.",
    perfectFor: ["Adventurous northern suburbs eaters", "Fourways evenings", "Dates that want something different", "When you need Fourways to deliver"],
    tags: ["Restaurant", "Fourways", "International", "Contemporary"],
    openingHours: "",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["Nomad restaurant Fourways Johannesburg", "restaurants Fourways Joburg", "international food Fourways"],
    status: "published",
    featured: false,
    datePosted: "2024-08-15",
  },
  {
    slug: "lupa-osteria-fourways",
    name: "Lupa Osteria",
    tagline: "Italian at Design Quarter, Fourways — 12.3K views and the pasta is the reason",
    category: "Restaurant",
    cuisine: "Italian",
    neighborhood: "Fourways",
    city: "Johannesburg",
    address: "Design Quarter, Fourways, Johannesburg",
    priceRange: "RR",
    tiktokViews: 12300,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=1200&q=80",
    excerpt: "I went to Lupa Osteria at Design Quarter in Fourways and the pasta made me stop mid-conversation. 12.3K views — the north has been missing a proper Italian and I think people agreed.",
    description: "Lupa Osteria at Design Quarter in Fourways hit 12.3K views on the Woman of Taste page and it filled a gap in the northern suburbs that I didn't realise I needed filled.\n\nI went for dinner. Ordered pasta. And then I stopped the conversation I was having because the food in front of me required attention.\n\nLupa is Italian — properly Italian in the way that means the pasta is made correctly, the sauce has real depth, and the whole meal feels like a hug that cost you something reasonable. The Design Quarter setting is relaxed and the service is warm.\n\nMy honest take: this is my Fourways Italian now. When I want comfort food with real craft behind it in the northern suburbs, Lupa Osteria is where I go. The pasta is the reason.",
    highlights: [
      "12.3K TikTok views on the WOT page",
      "Design Quarter location — accessible and well-positioned in Fourways",
      "Italian done with real confidence — the pasta is the thing",
      "Warm, relaxed setting that gets the tone right",
    ],
    mustTry: [
      { name: "Pasta", note: "This is the reason. Order whatever calls to you from the pasta section." },
      { name: "Antipasti to start", note: "Sets the tone for what the kitchen is doing" },
    ],
    vibe: "Warm, relaxed and genuinely Italian. The kind of dinner that makes you feel looked after.",
    perfectFor: ["Fourways dinners that want comfort", "When you need Italian done properly", "Group meals in the north", "Date nights that want warmth over drama"],
    tags: ["Restaurant", "Fourways", "Italian", "Pasta", "Design Quarter"],
    openingHours: "",
    reservations: true,
    website: "",
    instagramHandle: "",
    seoKeywords: ["Lupa Osteria Design Quarter Fourways Johannesburg", "Italian restaurants Fourways Joburg", "best pasta Johannesburg"],
    status: "published",
    featured: false,
    datePosted: "2024-12-10",
  },
  {
    slug: "dos-manos-melville",
    name: "Dos Manos",
    tagline: "Melville's Latin corner — 10.5K views and I went back the next week",
    category: "Restaurant",
    cuisine: "Mexican-Latin",
    neighborhood: "Melville",
    city: "Johannesburg",
    address: "Melville, Johannesburg",
    priceRange: "RR",
    tiktokViews: 10500,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1200&q=80",
    excerpt: "I went to Dos Manos in Melville and then went back the following week. That should tell you everything. 10.5K views — this is the Melville Latin spot that the neighbourhood has been needing.",
    description: "Dos Manos in Melville hit 10.5K views on the Woman of Taste page and I went back the following week. That's not something I say lightly.\n\nMelville's 7th Street has personality and Dos Manos fits it perfectly — it's neighbourhood, it's lively, and the Latin-Mexican food is the kind that makes you order more than you meant to.\n\nI had tacos and something from the cocktail list and spent the evening at the table longer than planned. The energy in there on a weekend night is exactly right — not too loud, not too precious, just a really good room.\n\nMy honest take: Dos Manos is now on my Melville rotation. It fills the Latin food gap in a neighbourhood that deserves it. The cocktails are worth it and the tacos are the reason to come back.",
    highlights: [
      "10.5K TikTok views on the WOT Melville feature",
      "Melville 7th Street location — walk the strip before dinner",
      "Latin-Mexican food that rewards ordering widely",
      "The kind of room that makes you stay longer than you planned",
    ],
    mustTry: [
      { name: "Taco selection", note: "Order across the menu — variety is the point" },
      { name: "Cocktail from the Latin list", note: "The drinks programme complements the food naturally" },
    ],
    vibe: "Lively, warm and thoroughly Melville. Latin flavours in a Joburg neighbourhood setting.",
    perfectFor: ["Group dinners in Melville", "When you need Latin food done right", "Relaxed date nights", "7th Street evenings"],
    tags: ["Restaurant", "Melville", "Mexican-Latin", "Group Dining", "7th Street"],
    openingHours: "",
    reservations: false,
    website: "",
    instagramHandle: "",
    seoKeywords: ["Dos Manos Melville Johannesburg", "Mexican restaurant Melville Joburg", "Latin food Johannesburg"],
    status: "published",
    featured: false,
    datePosted: "2024-08-20",
  },
  {
    slug: "sakhumzi-soweto",
    name: "Sakhumzi Restaurant",
    tagline: "Vilakazi Street, Soweto — 10.8K views and this was genuinely one of my favourite meals",
    category: "Restaurant",
    cuisine: "Traditional South African / Zulu",
    neighborhood: "Orlando West",
    city: "Soweto",
    address: "6980 Vilakazi St, Orlando West, Soweto",
    priceRange: "R",
    tiktokViews: 10800,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&q=80",
    excerpt: "I went to Sakhumzi on Vilakazi Street in Soweto and this one reminded me what food is actually for. 10.8K views — this is the meal I think about when I think about eating something that means something.",
    description: "Sakhumzi on Vilakazi Street in Soweto hit 10.8K views on the Woman of Taste page and it's one of the meals I think about most.\n\nVilakazi Street is historic — both Nelson Mandela and Desmond Tutu grew up on this road. Sakhumzi sits right there and has been feeding people properly for years. The buffet-style menu serves traditional South African food — umngqusho, chakalaka, pap, mogodu, samp, oxtail.\n\nI went in not knowing exactly what to expect and left genuinely moved. Not just by the food, which was proper and deeply satisfying, but by the whole experience of being there. The music, the community, the setting. It's a restaurant that connects you to something.\n\nMy honest take: every Joburger should go to Sakhumzi. Not for a photo opportunity — to actually eat. The food is excellent and the experience is one that stays with you. One of my favourite meals, full stop.",
    highlights: [
      "10.8K TikTok views on the WOT page",
      "Vilakazi Street location — one of the most significant streets in South Africa",
      "Traditional South African food done properly — umngqusho, pap, oxtail, chakalaka",
      "An experience that connects you to something beyond the meal",
    ],
    mustTry: [
      { name: "Umngqusho", note: "The traditional samp and beans. Deep, satisfying and worth every bite." },
      { name: "Oxtail", note: "Slow-cooked and genuinely excellent" },
      { name: "The full buffet", note: "Go broad. This is a food culture, not just a restaurant." },
    ],
    vibe: "Community, warmth and connection. This is what food is actually for.",
    perfectFor: ["When you want a meal that means something", "Discovering South African food culture", "Out-of-towners who deserve the real Joburg", "When Joburg needs to feel like home"],
    tags: ["Restaurant", "Soweto", "Traditional South African", "Vilakazi Street", "Cultural"],
    openingHours: "Daily 09:00–22:00",
    reservations: false,
    website: "",
    instagramHandle: "",
    seoKeywords: ["Sakhumzi restaurant Soweto Vilakazi Street", "traditional South African food Soweto", "restaurants Soweto Johannesburg"],
    status: "published",
    featured: false,
    datePosted: "2024-12-15",
  },
  {
    slug: "life-grand-cafe-waterfall",
    name: "Life Grand Café",
    tagline: "Waterfall's grand café — 10.5K views and I didn't want to leave",
    category: "Restaurant",
    cuisine: "Contemporary all-day café",
    neighborhood: "Waterfall",
    city: "Johannesburg",
    address: "Waterfall Corner, Midrand, Johannesburg",
    priceRange: "RR",
    tiktokViews: 10500,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&q=80",
    excerpt: "I went to Life Grand Café in Waterfall expecting a mall café. What I found was a European grand café that made me slow down and stay. 10.5K views — I think the name finally makes sense when you're sitting inside.",
    description: "Life Grand Café at Waterfall hit 10.5K views on the Woman of Taste page and it caught me off guard in the best way.\n\nI expected a standard mall coffee stop. What I found was a space that's genuinely spacious, light-filled, and designed to be spent in across the whole day. The 'grand café' format is European — the kind of place where you can arrive at 9am for a pastry and still be there at 1pm for lunch and it all makes sense.\n\nThe food is reliable and well-executed. The coffee is good. The light inside on a bright day is something else. I found a table and stayed for two hours.\n\nMy honest take: Life Grand Café is the Waterfall dining anchor that the precinct needed. If you're in Midrand or passing through Waterfall Corner, this is the stop. I go back whenever I'm in the area.",
    highlights: [
      "10.5K TikTok views on the WOT Waterfall feature",
      "European grand café format — built for lingering across the full day",
      "Waterfall Corner location — convenient with parking",
      "Light-filled space that actually makes you want to stay",
    ],
    mustTry: [
      { name: "Morning coffee and pastry", note: "The café starts well and the morning sets the tone" },
      { name: "Lunch plate", note: "Reliable, well-executed, generous" },
    ],
    vibe: "Grand, light-filled and unhurried. A European afternoon in the middle of Joburg.",
    perfectFor: ["Morning meetings", "All-day working sessions", "Post-gym brunch", "When the north needs somewhere that gets it right"],
    tags: ["Restaurant", "Café", "Waterfall", "All-Day Dining", "Midrand"],
    openingHours: "",
    reservations: false,
    website: "",
    instagramHandle: "",
    seoKeywords: ["Life Grand Café Waterfall Midrand Johannesburg", "grand café Waterfall Corner", "restaurants Midrand Joburg"],
    status: "published",
    featured: false,
    datePosted: "2024-08-25",
  },
  {
    slug: "the-tasting-room-pretoria",
    name: "The Tasting Room",
    tagline: "Pretoria's wine and tasting experience — and the one I didn't talk about enough",
    category: "Experience",
    cuisine: "Wine bar and sharing plates",
    neighborhood: "Pretoria",
    city: "Pretoria",
    address: "Pretoria, Gauteng",
    priceRange: "RR",
    tiktokViews: 11200,
    tiktokUrl: "https://www.tiktok.com/@pashieb_the_wot",
    coverImage: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=1200&q=80",
    excerpt: "I went to The Tasting Room in Pretoria for the experience and ended up staying far longer than planned. The kind of place that doesn't announce itself — it just rewards the people who find it.",
    description: "The Tasting Room in Pretoria is the kind of venue that doesn't need a massive following to be excellent.\n\nWhat this place does is simple and done well: curated wine experiences, beautifully assembled cheese and sharing boards, and an atmosphere that invites you to slow down and actually taste what's in front of you. The wine, gin and whiskey selection is thoughtful. The coffee is good. The macarons are worth arriving early for.\n\nThe space is warm without being precious. It's rated #4 among Pretoria's bars and tasting venues on Google — and sitting at that table, you understand why. The staff know their products, which makes the difference when you're there to actually learn something about what you're drinking.\n\nMy honest take: Pretoria keeps surprising me. This is one of those moments where I went in expecting a nice wine bar and left with a real experience. If you're in Pretoria and looking for something that goes beyond a restaurant — come here.",
    highlights: [
      "Wine, gin and whiskey tasting experiences in Pretoria",
      "Beautifully assembled cheese boards and sharing platters",
      "Rated #4 wine bar and tasting venue in Pretoria",
      "Macaron selection worth knowing about",
    ],
    mustTry: [
      { name: "Wine tasting flight", note: "Let them guide you. That's the point of a tasting room." },
      { name: "Cheese board", note: "A proper cheese selection. Don't rush through it." },
      { name: "The macaron selection", note: "Ask what's available. Arrive early for the best ones." },
    ],
    vibe: "Warm, unhurried, and genuinely educational. You leave knowing more than you arrived.",
    perfectFor: ["Wine lovers in Pretoria", "Slow afternoons with something to talk about", "Date experiences that feel considered", "Pretoria visitors who want more than a restaurant"],
    tags: ["Experience", "Wine Bar", "Pretoria", "Tasting", "Cheese Board"],
    openingHours: "",
    reservations: false,
    website: "",
    instagramHandle: "",
    seoKeywords: ["The Tasting Room Pretoria wine bar", "wine tasting Pretoria", "best wine bars Pretoria South Africa"],
    status: "published",
    featured: false,
    datePosted: "2025-01-15",
  },
];
