import { boolean, doublePrecision, integer, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";

export const bookingsTable = pgTable("bookings", {
  id: serial("id").primaryKey(),
  invoiceNumber: text("invoice_number").notNull(),
  status: text("status").notNull().default("PENDING"),
  eventId: text("event_id").notNull(),
  eventTitle: text("event_title").notNull(),
  eventDate: text("event_date").notNull(),
  eventLocation: text("event_location").notNull(),
  firstName: text("first_name").notNull(),
  surname: text("surname").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull().default(""),
  dietary: text("dietary"),
  quantity: integer("quantity").notNull(),
  pricePerTicket: doublePrecision("price_per_ticket").notNull(),
  totalAmount: doublePrecision("total_amount").notNull(),
  approvalToken: text("approval_token").unique(),
  declineToken: text("decline_token").unique(),
  tokenExpiresAt: timestamp("token_expires_at"),
  invoicePdfPath: text("invoice_pdf_path"),
  invoiceSentAt: timestamp("invoice_sent_at"),
  followup1SentAt: timestamp("followup1_sent_at"),
  followup2SentAt: timestamp("followup2_sent_at"),
  lastFollowupSentAt: timestamp("last_followup_sent_at"),
  paidAt: timestamp("paid_at"),
  qrToken: text("qr_token").unique(),
  checkedIn: boolean("checked_in").notNull().default(false),
  checkedInAt: timestamp("checked_in_at"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
